components/Intro.jsx
components/NgoCard.jsx
package-lock.json
package.json

In Intro Page and in NGO Cards and Shift the search bar to the top as you can see the difference in these pictures.
If you like this feature then pls merge my pull request under hacktoberfest 2024
Fixes #10

FIXAdding Animations Using Framer Motion #10

---

components/NgoCard.jsx

- Organizations card style improved for better visibility

organizations card style improved.

---

pages/frontend/displayJobs.jsx
pages/frontend/organizations.jsx

i hope you like the changes and do tell me if there's room for improvement :)

Enhanced title for a neat look

---

components/NavBar.jsx

i have added a subtle light blue color for highlighting so that it does the job and is visible too improving user experience.
i hope you like the changes

Highlight current tab in Navbar

---

CODE_OF_CONDUCT.md

add code of conduct file

---

components/NavBar.jsx

Hi, @Devmangrani 
I have resolved the issue with the hamburger menu on the fix-issue-#25 branch. Please review the changes and let me know if any adjustments are needed. Thanks!

Responsivness issue #25

---

components/Intro.jsx
components/Navbar.module.css.css

i have added the footer but i will add more and do some changes to it .
please accept the PR .

Added the footer 

---

components/Intro.jsx

Redesigned Footer section which seemed a little less interactive previously.
Added some icons instead of simple links of the social media sites along with some animation on the links.
Fixes #49

Improved footer design

---

pages/frontend/postAJob.jsx

fixes #48, now the user cannot input negative numbers and zero in salary and job vacancy. Also can't select past dates.

Fixed #48: Processing Invalid Input in Job Posting Form

---

pages/frontend/postAJob.jsx

made some few improvements to the UI of the "Post Jobs Page" to enhance it's appearance.
**changes**
- Input Box Styling: Added hover effects and shadows
- Replaced the old header and added a simple description
**Old layout**
**new Layout:**

UI enhancement/post jobs

---

Utils/NgoData.js
components.json
components/NavBar.jsx
components/NgoCard.jsx
components/ui/avatar.jsx
components/ui/badge.jsx
components/ui/button.jsx
components/ui/card.jsx
lib/utils.js
package-lock.json
package.json
pages/frontend/organizations.jsx
styles/globals.css
tailwind.config.js

Improved the UI for the Organisation page and navbar:
These changes focus on ensuring consistency in card sizes, improving layout alignment, and enhancing the overall user interface experience, along with a clean navbar
- Made the UI of organisation and navbarneat and professional 
- retained the animation 
Fixes: #3 , #58

Navbar and Organisation UI

---

components/Intro.jsx
components/NavBar.jsx
pages/frontend/displayJobs.jsx
pages/frontend/organizations.jsx
pages/frontend/postAJob.jsx
pages/frontend/postedJob.jsx
pages/index.js

- fixed merge conflicts from previous PR
- Added gradient background and description to home page.
- Changed the nav bar.
- minor styling of the titles of the pages

Update Home Page

---

components/Intro.jsx
components/NavBar.jsx
components/NgoCard.jsx
package-lock.json
package.json

Fixes-#38
- [ X] I have starred and forked the JobSewa repo.
- [ X] I have carefully read the instructions for contributing to the project.
- [ X] I have created a new page or section and placed it inside the appropriate folder.
- [ X] My contributions align with the current project structure and conventions.
- [ X] I have included any necessary images in a dedicated folder within `assets`, ensuring they are compressed and under 500kb.
- [ X] All images are in …

Enhancement: added UI changes on main page

---

components/Intro.jsx

fixes #80 
- [X ] I have starred and forked the JobSewa repo.
- [ X] I have carefully read the instructions for contributing to the project.
- [ X] I have created a new page or section and placed it inside the appropriate folder.
- [ X] My contributions align with the current project structure and conventions.
- [ X] I have included any necessary images in a dedicated folder within `assets`, ensuring they are compressed and under 500kb.
- [X ] All images are in …

fixed main page and navbar overlapping issue

---

pages/frontend/displayJobs.jsx

Closes #87
- I have fixed the alignment of searchbar on display job page

alignment of searchbar

---

components/JobsCard.jsx
pages/api/job/getAllJobs.js

Thank you for your contribution to **JobSewa**! We’re excited to work with you.

Search Results Container Overflow Bug fixed

---

pages/frontend/applyJob/[id].jsx

Thank you for your contribution to **JobSewa**! We’re excited to work with you.

Update job application form UI

---

components/JobsCard.jsx
pages/frontend/displayJobs.jsx

Thank you for your contribution to **JobSewa**! We’re excited to work with you.

Fixed UI Alignment Issues in View Jobs Section

---

pages/frontend/dashboard.jsx

Closes #100 
Made some css changes

fix: button height for smaller devices

---

styles/Navbar.module.css

Closes #103 
Made some changes in css file

fix: alignment of arrow in hamburger menu
